#!/bin/bash

# build the library
cd source/interpreter
make -q
if [ $? -ne 0 ]
then
    make || exit 1
fi


cd ../ide
qmake tetra.pro
make -q
if [ $? -ne 0 ]
then
    make
fi

echo "Finished Building Tetra!"

